# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 15

[[main]]
  name = "Other Projects"
  url = "#projects"
  weight = 40
  
[[main]]
  name = "Featured Work"
  url = "#featured"
  weight = 20

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
 name = "More"
  url = "#"
  hasChildren = true
  weight = 50

[[main]]
  parent = "More"
  name = "More Writing"
  url = "/more-writing/"
 # weight = 50

[[main]]
  parent = "More"
  name = "More Talks"
  url = "/more-talks/"
  weight = 55

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 70
